print("Welcome to the Band Name Generator")
print("What's name of the city you grew up in?")
cityName = input()
print("What's Your pet's name?")
petName = input()
print("Your band name could be ",cityName + " " + petName)